GROUP_LIST = ["KbFKSNqUkWs8RGVhiPpw4U"]
PHONE_NO_LIST = ["+917749984274"]
ALLOWED_DEVICE_ACCESS = ["anil-ubuntu", "AECC-IN-DIH049", "anil-kr-sahoo"]
THANK_YOU_MESSAGE = "Thank you for trade with AK Stock Monitoring. \nToday's trade is over."
ALLOW_NOTIFICATION = True
# List details
# [Grow url of stock, quantity you have, average price of your stocks, max threshold %]

user_stocks = {
    "my_stocks": [
        [
            "https://groww.in/stocks/bank-of-baroda",
            25,
            257.39
        ],
        [
            "https://groww.in/stocks/bank-of-india",
            12,
            119.88
        ],
        [
            "https://groww.in/stocks/bharat-petroleum-corporation-ltd",
            29,
            319.12
        ],
        [
            "https://groww.in/stocks/canara-bank",
            24,
            112.22
        ],
        [
            "https://groww.in/stocks/castrol-india-ltd",
            41,
            233.66
        ],
        [
            "https://groww.in/stocks/coal-india-ltd",
            46,
            373.69
        ],
        [
            "https://groww.in/stocks/gail-india-ltd",
            21,
            219.35
        ],
        [
            "https://groww.in/stocks/general-insurance-corporation-of-india-ltd",
            35,
            393.75
        ],
        [
            "https://groww.in/stocks/hcl-technologies-ltd",
            19,
            1276.40
        ],
        [
            "https://groww.in/stocks/hero-motocorp-ltd",
            22,
            4054.73
        ],
        [
            "https://groww.in/stocks/hindustan-zinc-ltd",
            35,
            537.41
        ],
        [
            "https://groww.in/stocks/hindustan-petroleum-corporation-ltd",
            26,
            363.78
        ],
        [
            "https://groww.in/stocks/infosys-ltd",
            10,
            1574.42
        ],
        [
            "https://groww.in/stocks/indian-oil-corporation-ltd",
            14,
            167.63
        ],
        [
            "https://groww.in/stocks/itc-ltd",
            17,
            429.85
        ],
        [
            "https://groww.in/stocks/national-aluminium-company-ltd",
            6,
            178.17
        ],
        [
            "https://groww.in/stocks/reliance-nippon-life-asset-management-ltd",
            26,
            549.04
        ],
        [
            "https://groww.in/stocks/nmdc-ltd",
            54,
            197.29
        ],
        [
            "https://groww.in/stocks/oracle-financial-services-software-ltd",
            15,
            6342.40
        ],
        [
            "https://groww.in/stocks/oil-natural-gas-corporation-ltd",
            42,
            258.93
        ],
        [
            "https://groww.in/stocks/petronet-lng-ltd",
            2,
            373.75
        ],
        [
            "https://groww.in/stocks/power-finance-corporation-ltd",
            61,
            442.90
        ],
        [
            "https://groww.in/stocks/power-grid-corporation-of-india-ltd",
            46,
            221.94
        ],
        [
            "https://groww.in/stocks/rec-ltd",
            60,
            493.15
        ],
        [
            "https://groww.in/stocks/sun-tv-network-ltd",
            4,
            785.23
        ],
        [
            "https://groww.in/stocks/union-bank-of-india",
            10,
            127.31
        ],
        [
            "https://groww.in/stocks/vedanta-ltd",
            51,
            324.70
        ],
        [
            "https://groww.in/stocks/wipro-ltd",
            3,
            605.28
        ]
    ]
}
