GROUP_LIST = ["KbFKSNqUkWs8RGVhiPpw4U"]
PHONE_NO_LIST = ["+917749984274"]
ALLOWED_DEVICE_ACCESS = ["anil-ubuntu", "AECC-IN-DIH049", "anil-kr-sahoo"]
THANK_YOU_MESSAGE = "Thank you for trade with AK Stock Monitoring. \nToday's trade is over."
ALLOW_NOTIFICATION = True
NOTIFIED_SELL_STOCK_URLS = list() # update this list if already notification sent
# List details
# [Grow url of stock, quantity you have, average price of your stocks, max threshold %]

user_stocks = {
    "my_stocks": [
        [
            "https://groww.in/stocks/ashok-leyland-ltd",
            5,
            235.12
        ],
        [
            "https://groww.in/stocks/bank-of-baroda",
            31,
            253.87
        ],
        [
            "https://groww.in/stocks/bank-of-india",
            19,
            114.32
        ],
        [
            "https://groww.in/stocks/bharat-petroleum-corporation-ltd",
            36,
            320.17
        ],
        [
            "https://groww.in/stocks/canara-bank",
            29,
            110.30
        ],
        [
            "https://groww.in/stocks/castrol-india-ltd",
            50,
            230.94
        ],
        [
            "https://groww.in/stocks/coal-india-ltd",
            46,
            373.69
        ],
        [
            "https://groww.in/stocks/colgatepalmolive-india-ltd",
            0,
            0
        ],
        [
            "https://groww.in/stocks/gail-india-ltd",
            29,
            215.55
        ],
        [
            "https://groww.in/stocks/general-insurance-corporation-of-india-ltd",
            51,
            405.36
        ],
        [
            "https://groww.in/stocks/hcl-technologies-ltd",
            23,
            1361.26
        ],
        [
            "https://groww.in/stocks/hero-motocorp-ltd",
            26,
            4191.65
        ],
        [
            "https://groww.in/stocks/hindustan-zinc-ltd",
            45,
            516.43
        ],
        [
            "https://groww.in/stocks/hindustan-petroleum-corporation-ltd",
            36,
            373.94
        ],
        [
            "https://groww.in/stocks/indraprastha-gas-ltd",
            3,
            417.52
        ],
        [
            "https://groww.in/stocks/infosys-ltd",
            15,
            1682.93
        ],
        [
            "https://groww.in/stocks/indian-oil-corporation-ltd",
            22,
            162.52
        ],
        [
            "https://groww.in/stocks/itc-ltd",
            28,
            450.12
        ],
        [
            "https://groww.in/stocks/lt-finance-holdings-ltd",
            5,
            150.43
        ],
        [
            "https://groww.in/stocks/mahanagar-gas-ltd",
            5,
            1264.94
        ],
        [
            "https://groww.in/stocks/mahindra-mahindra-financial-services-ltd",
            4,
            262.90
        ],
        [
            "https://groww.in/stocks/national-aluminium-company-ltd",
            24,
            192.46
        ],
        [
            "https://groww.in/stocks/ntpc-ltd",
            0,
            0
        ],
        [
            "https://groww.in/stocks/reliance-nippon-life-asset-management-ltd",
            42,
            599.59
        ],
        [
            "https://groww.in/stocks/nmdc-ltd",
            69,
            66.59
        ],
        [
            "https://groww.in/stocks/oil-india-ltd",
            2,
            430.25
        ],
        [
            "https://groww.in/stocks/oil-natural-gas-corporation-ltd",
            48,
            262.55
        ],
        [
            "https://groww.in/stocks/petronet-lng-ltd",
            6,
            340.54
        ],
        [
            "https://groww.in/stocks/power-finance-corporation-ltd",
            79,
            448.01
        ],
        [
            "https://groww.in/stocks/power-grid-corporation-of-india-ltd",
            51,
            234.97
        ],
        [
            "https://groww.in/stocks/rec-ltd",
            74,
            498.52
        ],
        [
            "https://groww.in/stocks/sun-tv-network-ltd",
            9,
            757.42
        ],
        [
            "https://groww.in/stocks/tech-mahindra-ltd",
            4,
            1707.13
        ],
        [
            "https://groww.in/stocks/union-bank-of-india",
            18,
            124.69
        ],
        [
            "https://groww.in/stocks/vedanta-ltd",
            57,
            337.72
        ],
        [
            "https://groww.in/stocks/wipro-ltd",
            6,
            302.64
        ]
    ]
}
