GROUP_LIST = ["KbFKSNqUkWs8RGVhiPpw4U"]
PHONE_NO_LIST = ["+917749984274"]
ALLOWED_DEVICE_ACCESS = ["anil-ubuntu"]
THANK_YOU_MESSAGE = "Thank you for trade with AK Stock Monitoring. \nToday's trade is over."
ALLOW_NOTIFICATION = True
# List details
# [Grow url of stock, quantity you have, average price of your stocks, max threshold %]

user_stocks = {
    "my_stocks": [
        [
            "https://groww.in/stocks/banco-products-india-ltd",
            20,
            514.05
        ],
        [
            "https://groww.in/stocks/bank-of-baroda",
            10,
            213.47
        ],
        [
            "https://groww.in/stocks/bosch-ltd",
            0,
            0
        ],
        [
            "https://groww.in/stocks/canara-bank",
            8,
            395.01
        ],
        [
            "https://groww.in/stocks/castrol-india-ltd",
            25,
            168.95
        ],
        [
            "https://groww.in/stocks/coal-india-ltd",
            25,
            290.86
        ],
        [
            "https://groww.in/stocks/general-insurance-corporation-of-india-ltd",
            0,
            0
        ],
        [
            "https://groww.in/stocks/hcl-technologies-ltd",
            10,
            1128.11
        ],
        [
            "https://groww.in/stocks/hero-motocorp-ltd",
            12,
            3115.27
        ],
        [
            "https://groww.in/stocks/hindustan-zinc-ltd",
            5,
            324.93
        ],
        [
            "https://groww.in/stocks/housing-urban-development-corporation-ltd",
            45,
            115.73
        ],
        [
            "https://groww.in/stocks/indian-oil-corporation-ltd",
            0,
            0
        ],
        [
            "https://groww.in/stocks/indraprastha-gas-ltd",
            17,
            420.61
        ],
        [
            "https://groww.in/stocks/infosys-ltd",
            8,
            1381.49
        ],
        [
            "https://groww.in/stocks/itc-ltd",
            10,
            424.65
        ],
        [
            "https://groww.in/stocks/mahindra-mahindra-financial-services-ltd",
            15,
            271.10
        ],
        [
            "https://groww.in/stocks/nmdc-ltd",
            24,
            148.6
        ],
        [
            "https://groww.in/stocks/ntpc-ltd",
            10,
            285.23
        ],
        [
            "https://groww.in/stocks/oil-india-ltd",
            36,
            300.38
        ],
        [
            "https://groww.in/stocks/oil-natural-gas-corporation-ltd",
            14,
            175.79
        ],
        [
            "https://groww.in/stocks/oracle-financial-services-software-ltd",
            9,
            4209.04
        ],
        [
            "https://groww.in/stocks/petronet-lng-ltd",
            7,
            236.68
        ],
        [
            "https://groww.in/stocks/piramal-enterprises-ltd",
            10,
            908.36
        ],
        [
            "https://groww.in/stocks/power-finance-corporation-ltd",
            17,
            354.04
        ],
        [
            "https://groww.in/stocks/power-grid-corporation-of-india-ltd",
            34,
            188.61
        ],
        [
            "https://groww.in/stocks/rec-ltd",
            19,
            385.56
        ],
        [
            "https://groww.in/stocks/reliance-nippon-life-asset-management-ltd",
            7,
            439.18
        ],
        [
            "https://groww.in/stocks/sun-tv-network-ltd",
            9,
            652.73
        ],
        [
            "https://groww.in/stocks/tata-consultancy-services-ltd",
            3,
            3626.07
        ],
        [
            "https://groww.in/stocks/tech-mahindra-ltd",
            10,
            1100.08
        ],
        [
            "https://groww.in/stocks/torrent-power-ltd",
            4,
            819.0
        ],
        [
            "https://groww.in/stocks/vedanta-ltd",
            29,
            247.27
        ],
        [
            "https://groww.in/stocks/wipro-ltd",
            3,
            605.28
        ]
    ]
}
